{% set version = '1.2.13' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-feature
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/feature_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/feature/feature_{{ version }}.tar.gz
  sha256: 2a07ff28442cca058a3ef9ed950737f1d9266aee9d74dda090caa2b117e0131e

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ks >=1.10.0
    - r-misc3d
    - r-rgl
  run:
    - r-base
    - r-ks >=1.10.0
    - r-misc3d
    - r-rgl

test:
  commands:
    - $R -e "library('feature')"           # [not win]
    - "\"%R%\" -e \"library('feature')\""  # [win]

about:
  home: http://www.mvstat.net/tduong
  license: GPL-2 | GPL-3
  summary: Local inferential feature significance for multivariate kernel density estimation.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: feature
# Version: 1.2.13
# Date: 2015-10-26
# Title: Local Inferential Feature Significance for Multivariate Kernel Density Estimation
# Author: Tarn Duong <tarn.duong@gmail.com> & Matt Wand <Matt.Wand@uts.edu.au>
# Maintainer: Tarn Duong <tarn.duong@gmail.com>
# Depends: R (>= 1.4.0)
# Imports: grDevices, graphics, ks (>= 1.10.0), misc3d, rgl, stats, tcltk
# Suggests: MASS
# Description: Local inferential feature significance for multivariate kernel density estimation.
# License: GPL-2 | GPL-3
# URL: http://www.mvstat.net/tduong
# NeedsCompilation: no
# Packaged: 2015-10-26 10:54:30 UTC; duongt
# Repository: CRAN
# Date/Publication: 2015-10-26 15:58:45
